# Generated by Django 5.1.1 on 2024-11-26 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('char_creation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race', models.CharField(max_length=50)),
                ('subrace', models.CharField(blank=True, max_length=50, null=True)),
                ('alignment', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='customization',
            name='character',
        ),
        migrations.RemoveField(
            model_name='customization',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='customization',
            name='spell',
        ),
        migrations.RemoveField(
            model_name='customization',
            name='weapon',
        ),
        migrations.DeleteModel(
            name='Character',
        ),
        migrations.DeleteModel(
            name='Equipment',
        ),
        migrations.DeleteModel(
            name='Spell',
        ),
        migrations.DeleteModel(
            name='Customization',
        ),
        migrations.DeleteModel(
            name='Weapon',
        ),
    ]
