# Generated by Django 5.1.1 on 2024-11-26 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('char_creation', '0004_remove_character_ability_score_character_charisma_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customization',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='customization',
            name='spell',
        ),
        migrations.RemoveField(
            model_name='customization',
            name='weapon',
        ),
        migrations.AddField(
            model_name='customization',
            name='equipments',
            field=models.ManyToManyField(to='char_creation.equipment'),
        ),
        migrations.AddField(
            model_name='customization',
            name='spells',
            field=models.ManyToManyField(to='char_creation.spell'),
        ),
        migrations.AddField(
            model_name='customization',
            name='weapons',
            field=models.ManyToManyField(to='char_creation.weapon'),
        ),
        migrations.AlterField(
            model_name='customization',
            name='character',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='char_creation.character'),
        ),
    ]
