# Generated by Django 5.1.1 on 2024-12-01 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('char_creation', '0005_remove_customization_equipment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='base_charisma',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='character',
            name='base_constitution',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='character',
            name='base_dexterity',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='character',
            name='base_intelligence',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='character',
            name='base_strength',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='character',
            name='base_wisdom',
            field=models.IntegerField(default=10),
        ),
    ]
