# Generated by Django 5.1.1 on 2024-12-01 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('char_creation', '0006_character_base_charisma_character_base_constitution_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='charisma',
            new_name='final_charisma',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='constitution',
            new_name='final_constitution',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='dexterity',
            new_name='final_dexterity',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='intelligence',
            new_name='final_intelligence',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='strength',
            new_name='final_strength',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='wisdom',
            new_name='final_wisdom',
        ),
    ]
